### DISCUSSION TITLE
Slack Title Target - No clickable link when executed through github actions

### DISCUSSION THREAD

**Discussion by phsamson** [test-results-reporter/reporter#267] [Q&A] [answered]
Hello,

I hope someone can help me.

Whenever I execute command to publish through Github Actions, there is no clickable link on the Slack Title Target. However, when I try to execute the command to publish in my terminal, it will have the clickable link that redirects me to my TestBeats report.

![Slack Title Target - No clickable link when executed through github actions](https://github.com/user-attachments/assets/a6d14982-06da-4037-8a8d-f2845b48d57f)

Also, I don't know how I can change this "demo-run" into like for example "Staging - End to End Tests". I already saw this discussion - https://github.com/test-results-reporter/testbeats/discussions/247 but I still not understand. Sorry I'm new to Playwright and Testbeats.

![image](https://github.com/user-attachments/assets/a23420e2-ced6-443b-8e41-023caa508fa0)

Please help?

**Comment by ASaiAnudeep** [comment, marked as answer]
Hello @phsamson ,

Please refer the environment variables that need to be set for publishing test results to testbeats with custom details.
https://docs.testbeats.com/others/environment-variables.html#testbeats-portal

```
TEST_BEATS_API_KEY=<secret>
TEST_BEATS_RUN=<run-name>
```

Make sure your env variables injected to Github Action step. For example

```yaml
 - name: Report Test Results
        run: npx testbeats publish -c testbeats.config.json
        env:
          TEST_BEATS_API_KEY: ${{ secrets.TEST_BEATS_API_KEY }}
          TEST_BEATS_RUN: 'Staging - E2E Tests'
```
